In [1]:
import numpy as np

In [2]:
from sklearn.preprocessing import MinMaxScaler

In [3]:
data = np.random.randint(0,100,(10,2))

In [4]:
data

array([[24, 97],
       [41, 71],
       [ 6, 94],
       [72,  7],
       [ 8,  3],
       [87, 66],
       [21, 15],
       [97, 81],
       [47, 21],
       [91, 22]])

In [5]:
scalar_model = MinMaxScaler()

In [6]:
type(scalar_model)

sklearn.preprocessing.data.MinMaxScaler

In [7]:
scalar_model.fit(data)

/home/priyank/anaconda3/envs/tfdeeplearning/lib/python3.5/site-packages/sklearn/utils/validation.py:590: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [8]:
scalar_model.transform(data)

array([[0.1978022 , 1.        ],
       [0.38461538, 0.72340426],
       [0.        , 0.96808511],
       [0.72527473, 0.04255319],
       [0.02197802, 0.        ],
       [0.89010989, 0.67021277],
       [0.16483516, 0.12765957],
       [1.        , 0.82978723],
       [0.45054945, 0.19148936],
       [0.93406593, 0.20212766]])

In [9]:
#can be done in one line but generally we fit on trining data then trasnform training data and test data on that

In [10]:
scalar_model.fit_transform(data)

/home/priyank/anaconda3/envs/tfdeeplearning/lib/python3.5/site-packages/sklearn/utils/validation.py:590: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[0.1978022 , 1.        ],
       [0.38461538, 0.72340426],
       [0.        , 0.96808511],
       [0.72527473, 0.04255319],
       [0.02197802, 0.        ],
       [0.89010989, 0.67021277],
       [0.16483516, 0.12765957],
       [1.        , 0.82978723],
       [0.45054945, 0.19148936],
       [0.93406593, 0.20212766]])

# # train test split

In [11]:
import pandas as pd

In [12]:
mydata = np.random.randint(0,101,(50,4))

In [13]:
mydata

array([[ 29,  48,  41,  32],
       [ 20,  32,  74,  29],
       [  4,  62,  75,  86],
       [ 16,  88,  18,   1],
       [ 18,  86,  93,  64],
       [ 83,  54,  68,  45],
       [ 94,  17,  82,  93],
       [ 87,  87,  47,  66],
       [  5,  35,  70,  42],
       [ 71,  11,  10,  27],
       [ 43,  17,  34,  75],
       [ 30,  93,  75,  64],
       [ 34,   1,   7,  29],
       [ 24,  10,  76,  98],
       [ 46,  29,  87,  80],
       [ 42,  55,  79,   4],
       [ 38,   9,  48,  43],
       [ 37,  35,  49,   4],
       [ 90,   7,  75,  88],
       [ 93,  81,  50,  42],
       [ 71,  30,   0,  89],
       [ 89,   9,   9,  10],
       [ 49,   8,  16,  35],
       [ 91,  20,  34,  51],
       [ 99,   3,  97,  97],
       [ 73,  15,  80,  55],
       [ 36,  44,  34,  60],
       [  2,  29,  18,   0],
       [ 55,   4,  32,  43],
       [ 21,  55,  46,  62],
       [ 19,  71,  35,   4],
       [ 89,  25,  29,  72],
       [ 65,  41,  85,  88],
       [ 20,  91,  19,  21],
       [100,  

In [22]:
df = pd.DataFrame(data = mydata, columns = ['f1','f2','f3','labels'])

In [23]:
df

f1  f2  f3  labels
0    29  48  41      32
1    20  32  74      29
2     4  62  75      86
3    16  88  18       1
4    18  86  93      64
5    83  54  68      45
6    94  17  82      93
7    87  87  47      66
8     5  35  70      42
9    71  11  10      27
10   43  17  34      75
11   30  93  75      64
12   34   1   7      29
13   24  10  76      98
14   46  29  87      80
15   42  55  79       4
16   38   9  48      43
17   37  35  49       4
18   90   7  75      88
19   93  81  50      42
20   71  30   0      89
21   89   9   9      10
22   49   8  16      35
23   91  20  34      51
24   99   3  97      97
25   73  15  80      55
26   36  44  34      60
27    2  29  18       0
28   55   4  32      43
29   21  55  46      62
30   19  71  35       4
31   89  25  29      72
32   65  41  85      88
33   20  91  19      21
34  100   8  55      97
35    7  18  86      66
36   62  77   7      74
37   88  41  41      98
38   71  12  39      29
39   66  58  95      96
40   48  80  95       9
41   75  84  67      33
42   59  61  48      30
43   40  26  94      38
44   77  46  12      10
45   12  40  92      89
46   66  53  13      87
47   84  22  72      78
48   66  35  11      66
49   55  12  43      83

In [26]:
X = df[['f1','f2','f3']]

In [32]:
y = df['labels']

In [33]:
y

0     32
1     29
2     86
3      1
4     64
5     45
6     93
7     66
8     42
9     27
10    75
11    64
12    29
13    98
14    80
15     4
16    43
17     4
18    88
19    42
20    89
21    10
22    35
23    51
24    97
25    55
26    60
27     0
28    43
29    62
30     4
31    72
32    88
33    21
34    97
35    66
36    74
37    98
38    29
39    96
40     9
41    33
42    30
43    38
44    10
45    89
46    87
47    78
48    66
49    83
Name: labels, dtype: int64

In [34]:
from sklearn.model_selection import train_test_split

In [40]:
X_train, X_test, y_train, y_test = train_test_split(
...     X, y, test_size=0.3, random_state=101)  # random_state is like random seed , si that we get same split each time

In [41]:
X_train.shape

(35, 3)

In [42]:
X_test.shape

(15, 3)