In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.3.0


In [12]:
hello = tf.constant("Hello ")

In [13]:
world = tf.constant("World")

In [14]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [15]:
print(hello)

Tensor("Const_2:0", shape=(), dtype=string)


In [16]:
with tf.Session() as sess:
    result = sess.run(hello + world)

In [17]:
result

b'Hello World'

In [18]:
a = tf.constant(10)

In [19]:
b = tf.constant(20)

In [20]:
a+b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [21]:
a+b

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [22]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [23]:
result

30

In [25]:
const = tf.constant(10)

In [26]:
fill_mat = tf.fill((4,4),10)

In [27]:
myzeros = tf.zeros((4,4))

In [28]:
myones = tf.ones((4,4))

In [29]:
myrandn = tf.random_normal((4,4), mean=0, stddev=1.0)

In [30]:
myrandu = tf.random_uniform((4,4) ,minval= 0, maxval=1)

In [31]:
my_ops = [const, fill_mat, myzeros, myones, myrandn, myrandu]

# Interactive session

In [32]:
sess = tf.InteractiveSession()

In [36]:
for op in my_ops:
    print(sess.run(op)) # print(op.eval())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[-0.22473639  0.18426485  0.83696735  0.95769817]
 [ 0.02643929 -0.34495512 -0.01125736 -0.29227147]
 [ 0.26243588  0.0396918   0.259587   -0.8925819 ]
 [-1.2701212  -0.23000893  1.1256374  -0.6864185 ]]


[[0.02989841 0.5798949  0.92475796 0.6429384 ]
 [0.26159298 0.57436275 0.24107361 0.37126553]
 [0.6355586  0.30517328 0.61259675 0.47257555]
 [0.5798503  0.92844546 0.44394147 0.2110486 ]]




In [37]:
a = tf.constant([[1,2],
                [3,4]])

In [38]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [39]:
b = tf.constant([[10],[100]])

In [40]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [41]:
result = tf.matmul(a,b)

In [42]:
sess.run(result)

array([[210],
       [430]], dtype=int32)

In [43]:
result.eval()

array([[210],
       [430]], dtype=int32)